version: '3.8'

services:
  app:
    image: php:8.1-apache
    container_name: projeto_palco_app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: bd_projpalco
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    build:
      context: .
      dockerfile: Dockerfile.APP


  db:
    image: mysql:8.0
    container_name: projeto_palco_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_projpalco
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: projeto_palco_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
